# Site settings
title:        "Coulee Hop - La Crosse, WI"
description:  "Lindy hop, east coast swing, west coast swing, balboa, shag, charleston, blues, and traditional jazz in the Coulee Region"
baseurl:      "" # the subpath of your site, e.g. /blog/
url:          "https://couleehop.github.io/" # the base hostname & protocol for your site
permalink:    /:year/:title
github:       "couleehop"
twitter:      "couleehop"
email:        "couleehop@gmail.com"
disqus-id:    "" #leave blank if you dont want comments.

# Build settings
markdown:     kramdown
sass:
    style: :compressed
